#!/bin/bash
################################################################################
#
# Copyright (c) 2015, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file build_oai
# brief OAI automated build tool that can be used to install, compile, run OAI.
# author  Navid Nikaein, Lionel GAUTHIER, Laurent Thomas


################################
# include helper functions
################################
ORIGIN_PATH=$PWD
THIS_SCRIPT_PATH=$(dirname $(readlink -f $0))
source $THIS_SCRIPT_PATH/tools/build_helper

trap handle_ctrl_c INT

function main() {
  ############################################
  # setting and printing OAI envs, we should check here
  ############################################

  echo_info "Setting the CONTROLLER PATHS ..."

  # set_openair_env
  cecho "CONTROLLER_DIR    = $CONTROLLER_DIR" $green

  # if [ "$CLEAN_ALL" = "1" ] ; then
  #   clean_all_files
  #   echo_info "Erased all previously producted files"
  # fi

  dbin=$CONTROLLER_DIR/targets/bin
  dlog=$CONTROLLER_DIR/cmake_targets/log
  mkdir -p $dbin $dlog
 
  echo_info "Building the compilation directives ..."

  DIR=$CONTROLLER_DIR/cmake_targets

  controller_build_dir=controller
  controller_exec=controller

  # CONTROLLER compilation
  # [ "$CLEAN" = "1" ] && rm -rf $DIR/$controller_build_dir/build
  mkdir -p $DIR/$controller_build_dir/build
  cmake_file=$DIR/$controller_build_dir/CMakeLists.txt
  echo "cmake_minimum_required(VERSION 2.8)"   >  $cmake_file
  # echo "set ( RRC_ASN1_VERSION \"${REL}\")"      >>  $cmake_file
  # echo "set ( ENABLE_VCD_FIFO $VCD_TIMING )"     >>  $cmake_file
  # echo "set ( RF_BOARD \"${HW}\")"               >>  $cmake_file
  # echo "set ( TRANSP_PRO \"${TP}\")"             >>  $cmake_file
  # echo "set(PACKAGE_NAME \"${lte_exec}\")"       >>  $cmake_file
  # echo "set (LOWLATENCY \"${LOWLATENCY_FLAG_USER}\" )"    >>$cmake_file
  echo 'include(${CMAKE_CURRENT_SOURCE_DIR}/../CMakeLists.txt)' >> $cmake_file
  cd  $DIR/$controller_build_dir/build
  cmake ..

  echo_info "Compiling $controller_exec"
  compilations \
  $controller_build_dir $controller_exec \
  $controller_exec $dbin/$controller_exec

}

main "$@"
